import AppKit
import Foundation

@MainActor
public final class ClipboardMonitor {
    public static let shared = ClipboardMonitor()

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    public var isIgnoringNextChange: Bool = false

    private let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.dstoecker.x-safari-password"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    private init() {
        self.lastChangeCount = pasteboard.changeCount
    }

    public func start() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.35, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkForChanges()
            }
        }
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    public func markSelfCopy() {
        isIgnoringNextChange = true
    }

    private func checkForChanges() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        if isIgnoringNextChange {
            isIgnoringNextChange = false
            return
        }

        // Check for password manager concealed types
        if let types = pasteboard.types {
            for concealed in concealedTypes {
                if types.contains(concealed) {
                    return
                }
            }
        }

        // 1. Check for file URLs
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL], !urls.isEmpty {
            let paths = urls.map { $0.path }
            let preview = urls.map { $0.lastPathComponent }.joined(separator: ", ")
            let item = ClipboardItem(
                type: .fileURL,
                filePaths: paths,
                preview: preview
            )
            ClipboardStore.shared.add(item: item)
            return
        }

        // 2. Check for images (PNG, TIFF)
        if let image = NSImage(pasteboard: pasteboard) {
            // Get PNG representation if possible
            if let tiffData = image.tiffRepresentation,
               let bitmap = NSBitmapImageRep(data: tiffData),
               let pngData = bitmap.representation(using: .png, properties: [:]) {
                let item = ClipboardItem(
                    type: .image,
                    imageData: pngData,
                    preview: "Görsel • \(Int(image.size.width))×\(Int(image.size.height))"
                )
                ClipboardStore.shared.add(item: item)
                return
            }
        }

        // 3. Check for plain string
        if let string = pasteboard.string(forType: .string), !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let cleanedString = string.trimmingCharacters(in: .whitespacesAndNewlines)
            let preview = cleanedString.replacingOccurrences(of: "\n", with: " ")
                .prefix(120)

            let rtfData = pasteboard.data(forType: .rtf)

            let item = ClipboardItem(
                type: .text,
                textContent: string,
                rtfData: rtfData,
                preview: String(preview)
            )
            ClipboardStore.shared.add(item: item)
            return
        }
    }
}
